name: Deploy

on:
    push:
      branches: [ master ]

jobs:

  run-playbook:
    uses: saubermacherag/ansible-playbook-docker-action@v1.3
    with:
      playbookName: 'main.yml'
      inventoryFile: '.ansible/inventory'
      keyFile: ".ansible/ssh-key"
      keyFileVaultPass: ${{ secrets.KEYFILE_VAULT_PASS }}
      extraVars: "-e ansible_ssh_user=${{ secrets.ANSIBLE_USER }}"